version: "3.7"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 010204
      POSTGRES_DB: pixMessages
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "8080:3000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "npx sequelize db:migrate && npm start"
    environment:
      NODE_ENV: production
      DB_USERNAME: postgres
      DB_PASSWORD: 010204
      DB_DATABASE: pixMessages
      DB_HOST: db
      DB_PORT: 5432

    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
